###
# @name admin_jwt_login
Post http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "admin@user.com",
    "password" : "secret"
}

###
get http://localhost:3000/esquenta/prefixo

###
get http://localhost:3000/admin/products

###
# @name  createProduct
post http://localhost:3000/admin/products/
Content-Type: application/json

{
   "name": "Product 1",
   "slug": "Product-187115614",
   "description": "Description of product 1",
   "price": 9.30
}

####
@productId = {{createProduct.response.body.id}}

###
Get   http://localhost:3000/admin/admin/products/{{productId}}

###
Patch http://localhost:3000/admin/products/{{productId}}
Content-Type: application/json

{
    "slug": "xpto"
    
}


###
Delete http://localhost:3000/admin/products/{{productId}}




### open products

GET http://localhost:3000/products/?name=product 1

###
GET http://localhost:3000/products/Product-10


