get http://localhost:3000/esquenta/hello

###
get http://localhost:3000/products

###
# @name  createProduct
post http://localhost:3000/products/
Content-Type: application/json

{
   "name": "Product 1",
   "slug": "Product-1ggdfgs",
   "description": "Description of product 1",
   "price": 9.30
}

####
@productId = {{createProduct.response.body.id}}

###
Get   http://localhost:3000/products/1

###
Patch http://localhost:3000/products/cm5uj2np30000u7xsmxuztaub
Content-Type: application/json

{
    "slug": "Product-2"
    
}


###
Delete http://localhost:3000/products/{{productId}}





